<a href="https://colab.research.google.com/github/marsrabin13/DI_Bootcamp/blob/colab/Week_8_Day_2_ExercisesXP_Student.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercises XP: Student Notebook

For each exercise, the **Instructions** from the plateform are guided, and the **Guidance** explains exactly what you must do to complete the task.

## What you will learn
- How to clearly define and articulate a machine learning problem statement.

- The process of data collection, including identifying relevant data types and potential data sources.
Skills in feature selection and justification for machine learning models, particularly in the context of loan default prediction.

- Understanding of different types of machine learning models and their suitability for various real-world scenarios.

- Techniques and strategies for evaluating the performance of different machine learning models, including choosing appropriate metrics and understanding their implications.

## What you will create
- A detailed problem statement and data collection plan for a loan default prediction project, including identification of key data types and sources.
- A comprehensive feature selection analysis for a hypothetical loan default prediction dataset.
- A theoretical evaluation strategy for three different types of machine learning models, addressing the unique challenges and metrics relevant to each model type.
- Thoughtful analyses and justifications for choosing specific machine learning approaches for varied scenarios such as stock price prediction, library organization, and robot navigation.
- A document or presentation that showcases your understanding and approach to evaluating and optimizing machine learning models in diverse contexts.

## 🌟 Exercise 1 : Defining the Problem and Data Collection for Loan Default Prediction

### Instructions
- Write a clear problem statement for predicting loan defaults.
- Identify and list the types of data you would need for this project (e.g., personal details of applicants, credit scores, loan amounts, repayment history).
- Discuss the sources where you can collect this data (e.g., financial institution’s internal records, credit bureaus).

**Expected Output:** A document detailing the problem statement and a comprehensive plan for data collection, including data types and sources.

### Guidance
- Please write your answer as a short document. Begin by stating the prediction objective in a complete sentence that names the target variable and the decision it will support. Then, describe the data types you would collect in complete sentences. For each data type, explain in one sentence why it could help predict loan defaults.

- After that, name realistic data sources in complete sentences, and briefly describe how you would obtain or integrate each source.

- Finally, include one paragraph that explains risks and constraints such as privacy, regulation, data quality, sampling bias, and governance.

### Your answer
> To-Do:
Please write your full answer below using complete sentences and clear structure.

### Problem Statement
The goal is to predict the binary target of loan default to assist financial institutions in risk assessment and approval decisions.

### Data Collection Plan
We will collect applicant demographics (age, income) to assess financial stability, credit scores and payment history to evaluate past reliability, and loan specifics (amount, term) to understand the debt obligation. Data will be sourced from internal bank records via database queries and credit bureau reports integrated through secure APIs. Macroeconomic data like unemployment rates will also be pulled from public databases to provide economic context.

### Risks and Constraints
Key constraints include ensuring GDPR/CCPA compliance for data privacy and managing data quality issues like missing values. We must also address sampling bias in historical records and implement strict data governance to ensure secure, ethical use of sensitive information.

### Quick Resources
- [Pandas Docs](https://pandas.pydata.org/docs/): Data manipulation.
- [Scikit-learn](https://scikit-learn.org/stable/): Preprocessing and metrics.
- [ML Guide](https://developers.google.com/machine-learning/crash-course): Problem framing and evaluation.

## 🌟 Exercise 2 : Feature Selection and Model Choice for Loan Default Prediction

### Instructions
From this dataset, identify which features might be most relevant for predicting loan defaults.
Justify your choice of features.

### Guidance
- First, identify the features that you believe are most relevant, and write their names in a sentence.
Then, provide a justification in complete sentences that explains how each selected feature relates to the likelihood of default.

- If you decide to exclude common features, write one sentence for each excluded feature to explain why it is not appropriate in this context.

- Conclude with two complete sentences that explain how you would encode categorical features and how you would impute missing values.

In [8]:
import pandas as pd
import os

# Priority 1: Check the current folder as per user context
local_path = './loan_prediction.csv'
# Priority 2: Check the full Drive path
drive_path = '/content/drive/MyDrive/Colab Notebooks/loan_prediction.csv'

try:
    if os.path.exists(local_path):
        df = pd.read_csv(local_path)
        print(f"Successfully loaded data from: {local_path}")
    elif os.path.exists(drive_path):
        df = pd.read_csv(drive_path)
        print(f"Successfully loaded data from: {drive_path}")
    else:
        raise FileNotFoundError
except (FileNotFoundError, Exception):
    print("Local file not found. Loading from verified public repository...")
    url = 'https://raw.githubusercontent.com/dphi-official/Datasets/master/Loan_Data/loan_train.csv'
    df = pd.read_csv(url)

print(f"Dataset Shape: {df.shape}")
display(df.head())
print("\nColumn Data Types:")
print(df.dtypes)
print("\nMissing per column:")
display(df.isna().sum().sort_values(ascending=False))

Local file not found. Loading from verified public repository...
Dataset Shape: (491, 14)

,Unnamed: 0,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,0,LP002305,Female,No,0,Graduate,No,4547,0.0,115.0,360.0,1.0,Semiurban,1
1,1,LP001715,Male,Yes,3+,Not Graduate,Yes,5703,0.0,130.0,360.0,1.0,Rural,1
2,2,LP002086,Female,Yes,0,Graduate,No,4333,2451.0,110.0,360.0,1.0,Urban,0
3,3,LP001136,Male,Yes,0,Not Graduate,Yes,4695,0.0,96.0,NaN,1.0,Urban,1
4,4,LP002529,Male,Yes,2,Graduate,No,6700,1750.0,230.0,300.0,1.0,Semiurban,1

Column Data Types:
Unnamed: 0             int64
Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status            int64
dtype: object

Missing per column:

Credit_History       43
Self_Employed        29
LoanAmount           16
Loan_Amount_Term     13
Gender               10
Dependents            9
Married               1
Education             0
Unnamed: 0            0
Loan_ID               0
CoapplicantIncome     0
ApplicantIncome       0
Property_Area         0
Loan_Status           0
dtype: int64

In [11]:
import pandas as pd

# Selected features based on the loaded dataset
selected_features = [
    "Credit_History",
    "ApplicantIncome",
    "CoapplicantIncome",
    "LoanAmount",
    "Education",
    "Property_Area",
    "Married"
]

# 1. Handling Missing Values
# Continuous: Median Imputation
df['LoanAmount'] = df['LoanAmount'].fillna(df['LoanAmount'].median())

# Categorical: Mode Imputation (index 0 gets the most frequent value)
df['Credit_History'] = df['Credit_History'].fillna(df['Credit_History'].mode()[0])
df['Married'] = df['Married'].fillna(df['Married'].mode()[0])

# 2. One-Hot Encoding for categorical features
# This converts 'Education', 'Property_Area', and 'Married' into binary columns
df_encoded = pd.get_dummies(df[selected_features], columns=['Education', 'Property_Area', 'Married'], drop_first=True)

print("Preprocessing Complete:")
print(f"Original columns: {selected_features}")
print(f"Encoded DataFrame shape: {df_encoded.shape}")
display(df_encoded.head())

print("\nSummary of strategy:")
print("- One-Hot Encoding applied to categorical columns.")
print("- Missing 'LoanAmount' filled with Median.")
print("- Missing 'Credit_History'/'Married' filled with Mode.")

Preprocessing Complete:
Original columns: ['Credit_History', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Education', 'Property_Area', 'Married']
Encoded DataFrame shape: (491, 8)

,Credit_History,ApplicantIncome,CoapplicantIncome,LoanAmount,Education_Not Graduate,Property_Area_Semiurban,Property_Area_Urban,Married_Yes
0,1.0,4547,0.0,115.0,False,True,False,False
1,1.0,5703,0.0,130.0,True,False,False,True
2,1.0,4333,2451.0,110.0,False,False,True,True
3,1.0,4695,0.0,96.0,True,False,True,True
4,1.0,6700,1750.0,230.0,False,True,False,True

Summary of strategy:
- One-Hot Encoding applied to categorical columns.
- Missing 'LoanAmount' filled with Median.
- Missing 'Credit_History'/'Married' filled with Mode.

### Your justification
I have selected **Credit_History, ApplicantIncome, CoapplicantIncome, LoanAmount, Education, Property_Area, and Married** as the most relevant features.

*   **Credit_History** is the strongest predictor as it reflects past repayment behavior.
*   **ApplicantIncome** and **CoapplicantIncome** determine the total household capacity to repay the debt.
*   **LoanAmount** is critical because higher debt-to-income ratios increase default risk.
*   **Education** and **Married** status often correlate with financial stability and earning potential.

I have excluded **Loan_ID** because it is a unique identifier with no predictive power, and **Unnamed: 0** as it is just an index.

To handle categorical features like `Gender` or `Property_Area`, I would use **One-Hot Encoding** to convert them into numerical format. For missing values, I would use **Mode Imputation** for categorical variables like `Credit_History` and **Median Imputation** for continuous variables like `LoanAmount` to avoid the influence of outliers.

## 🌟 Exercise 3 : Training, Evaluating, and Optimizing the Model

### Instructions
Which model(s) would you pick for a Loan Prediction ?
Outline the steps to evaluate the model’s performance, mentioning specific metrics that would be relevant to evaluate the model.

### Guidance
- Begin by naming one or two candidate models in a complete sentence and explain why each model is suitable for this problem.

- Next, describe an evaluation plan in complete sentences that covers the data split, the cross-validation strategy, the metrics you will report, and how you will choose a decision threshold.

- Then, explain in complete sentences how you will address class imbalance using stratification, class weights, or resampling.

- Finally, state in one or two complete sentences how you would iterate on hyperparameters to improve performance while avoiding data leakage.

In [12]:

# This piece of code is already prefilled, run it to execute it and see the results.
# It demonstrates standard classification metrics for binary loan default prediction.

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, average_precision_score, confusion_matrix, classification_report

# Please replace these placeholders with your true labels and predicted probabilities.
y_true = [0,1,0,1,0,0,1,0,1,0]            # placeholder labels
y_pred_proba = [0.05,0.80,0.10,0.65,0.20,0.15,0.70,0.30,0.85,0.25]  # placeholder probabilities

# You should set a decision threshold that reflects the precision–recall trade-off for your business case.
threshold = 0.5
y_pred = [1 if p >= threshold else 0 for p in y_pred_proba]

print("Accuracy:", round(accuracy_score(y_true, y_pred), 4))
print("Precision:", round(precision_score(y_true, y_pred, zero_division=0), 4))
print("Recall:", round(recall_score(y_true, y_pred, zero_division=0), 4))
print("F1-score:", round(f1_score(y_true, y_pred, zero_division=0), 4))
print("ROC-AUC:", round(roc_auc_score(y_true, y_pred_proba), 4))
print("PR-AUC (Average Precision):", round(average_precision_score(y_true, y_pred_proba), 4))
print("\nConfusion matrix:\n", confusion_matrix(y_true, y_pred))
print("\nClassification report:\n", classification_report(y_true, y_pred, zero_division=0))

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1-score: 1.0
ROC-AUC: 1.0
PR-AUC (Average Precision): 1.0

Confusion matrix:
 [[6 0]
 [0 4]]

Classification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00         4

    accuracy                           1.00        10
   macro avg       1.00      1.00      1.00        10
weighted avg       1.00      1.00      1.00        10

### Your answer
For this loan default prediction task, I would choose **Logistic Regression** and **Random Forest** models. Logistic Regression is suitable because it provides clear coefficients for risk factor interpretation, while Random Forest is robust to outliers and can handle the non-linear relationships often found in financial data.

My evaluation plan involves splitting the data into a **70/30 train-test split** and using **5-fold stratified cross-validation** to ensure stable performance estimates. I will prioritize **F1-Score** and **Recall** as my primary metrics, as the cost of missing a potential default (False Negative) is significantly higher than the cost of a manual review for a false alarm. I will select the final decision threshold by analyzing the **Precision-Recall curve** to balance institutional risk appetite.

To address the class imbalance (as defaults are typically rarer than successful repayments), I will use **SMOTE (Synthetic Minority Over-sampling Technique)** or adjust the **class_weight** parameter in the models to penalize misclassifications of the minority class. Finally, I will iterate on hyperparameters using a **Randomized Search** while ensuring all preprocessing steps are contained within a pipeline to avoid data leakage.

## 🌟 Exercise 4 : Designing Machine Learning Solutions for Specific Problems

### Instructions
For each of these scenario, decide which type of machine learning would be most suitable. Explain.

Predicting Stock Prices : predict future prices
Organizing a Library of Books : group books into genres or categories based on similarities.
Program a robot to navigate and find the shortest path in a maze.

### Guidance
Please identify the appropriate machine learning paradigm for each scenario in complete sentences and justify your choice.

For each scenario, write one complete sentence that describes the input data, one complete sentence that describes the output, and one complete sentence that describes the learning signal or objective.

### Your answer

**1. Predicting Stock Prices**
**Supervised Learning (Regression)** is the most suitable paradigm because we are predicting a continuous numerical value based on historical data. The input data would consist of historical stock prices, trading volumes, and technical indicators over a specific timeframe. The output is the predicted price of the stock at a future point in time. The learning signal is the difference between the model's prediction and the actual observed market price (e.g., Mean Squared Error).

**2. Organizing a Library of Books**
**Unsupervised Learning (Clustering)** is the best choice here as we want to discover hidden patterns and group books without pre-existing labels. The input data includes text-based features such as book titles, summaries, and keyword frequencies. The output is a set of distinct clusters where each group contains books with similar themes or genres. The objective is to maximize the similarity of items within a cluster while maximizing the difference between different clusters.

**3. Robot Maze Navigation**
**Reinforcement Learning** is the appropriate paradigm because the robot must learn an optimal sequence of actions through trial and error. The input data consists of the robot's current state, including its coordinates in the maze and sensor readings (like distance to walls). The output is the specific action the robot should take next, such as moving forward, turning left, or turning right. The learning signal is a reward system where the robot receives a positive reward for reaching the exit and a penalty for hitting walls or taking too many steps.

## 🌟 Exercise 5 : Designing an Evaluation Strategy for Different ML Models

### Instructions
- Select three types of machine learning models: one from supervised learning (e.g., a classification model), one from unsupervised learning (e.g., a clustering model), and one from reinforcement learning. - For the supervised model, outline a strategy to evaluate its performance, including the choice of metrics (like accuracy, precision, recall, F1-score) and methods (like cross-validation, ROC curves).
- For the unsupervised model, describe how you would assess the effectiveness of the model, considering techniques like silhouette score, elbow method, or cluster validation metrics.
- For the reinforcement learning model, discuss how you would measure its success, considering aspects like cumulative reward, convergence, and exploration vs. exploitation balance.
- Address the challenges and limitations of evaluating models in each category.

### Guidance
- Please write a separate paragraph for each of the three model categories.
- In the supervised paragraph, describe your validation plan and list the metrics you will report in complete sentences.
- In the unsupervised paragraph, explain how you would measure cluster quality or structure in complete sentences and mention any diagnostic plots.
- In the reinforcement learning paragraph, describe how you would track cumulative reward, assess convergence, and balance exploration and exploitation using complete sentences.
Conclude with one complete sentence per category that states a key evaluation challenge.

In [13]:

# This piece of code is already prefilled, run it to execute it and see the results.
# Supervised classification metrics template with placeholders.

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, average_precision_score

# Replace these placeholders with your real outputs.
y_true = [0,1,1,0,1,0,0,1,0,1]
y_pred_proba = [0.1,0.7,0.8,0.2,0.6,0.3,0.4,0.9,0.2,0.85]
threshold = 0.5
y_pred = [1 if p >= threshold else 0 for p in y_pred_proba]

print("Accuracy:", round(accuracy_score(y_true, y_pred), 4))
print("Precision:", round(precision_score(y_true, y_pred, zero_division=0), 4))
print("Recall:", round(recall_score(y_true, y_pred, zero_division=0), 4))
print("F1-score:", round(f1_score(y_true, y_pred, zero_division=0), 4))
print("ROC-AUC:", round(roc_auc_score(y_true, y_pred_proba), 4))
print("PR-AUC (Average Precision):", round(average_precision_score(y_true, y_pred_proba), 4))

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1-score: 1.0
ROC-AUC: 1.0
PR-AUC (Average Precision): 1.0

In [14]:

# This piece of code is already prefilled, run it to execute it and see the results.
# Unsupervised clustering metrics template with synthetic data.

from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

X, _ = make_blobs(n_samples=300, centers=3, random_state=42)
kmeans = KMeans(n_clusters=3, n_init="auto", random_state=42)
labels = kmeans.fit_predict(X)
sil = silhouette_score(X, labels)
print("Silhouette score (higher is better):", round(sil, 4))

print("Please explain in complete sentences when you would use the elbow method and how you would interpret it.")

Silhouette score (higher is better): 0.848
Please explain in complete sentences when you would use the elbow method and how you would interpret it.

### Your answer

**Supervised Learning (Classification):** I will use a stratified K-fold cross-validation strategy to ensure the model generalizes well across different subsets of the data. The primary metrics reported will be F1-score and Recall to account for potential class imbalances, alongside ROC-AUC to evaluate the classification threshold performance. A key evaluation challenge in supervised learning is the presence of biased historical labels that can perpetuate unfairness.

**Unsupervised Learning (Clustering):** To assess cluster quality, I will calculate the Silhouette Score to measure how similar an object is to its own cluster compared to others. I will also utilize the Elbow Method by plotting the within-cluster sum of squares (WCSS) to identify the optimal number of clusters. A major challenge in unsupervised learning is the lack of a ground truth, making it difficult to objectively verify if the discovered clusters are meaningful.

**Reinforcement Learning:** I will track the cumulative reward over time to measure the agent's learning progress and observe the reward curve to assess convergence to an optimal policy. The balance between exploration and exploitation will be monitored using an epsilon-decay strategy to ensure the agent sufficiently searches the environment before committing to known paths. A significant challenge in reinforcement learning is the high sensitivity to reward function design, where an agent might learn to exploit technicalities rather than solve the intended task.